### ISSUE TITLE
Failing to recognize Solidity files

### ISSUE THREAD

**Issue by zarifpour** [zarifpour/zed-solidity#1]
The extension has been observed to load correctly. However, there is an issue where it fails to recognize Solidity files and does not automatically set the language for these files when the extension is loaded.

![CleanShot 2024-02-25 at 03 38 02 on Zed — example sol — zed-solidity](https://github.com/zarifpour/zed-solidity/assets/16494335/b7ae72c6-98a3-4b66-b850-12b76693d96d)

**Comment by meetmangukiya** [comment]
How are you verifying that its loading?

**Comment by zarifpour** [comment]
> How are you verifying that its loading?

When I say `loading`, I mean that the extension is being recognized by Zed and I have the option to select it as a file language.

**Comment by zarifpour** [comment]
There might be an issue with the language configuration, or there could be another missing component.

**Comment by meetmangukiya** [comment]
Yeah i meant how do you check the extension is loaded in zed

**Comment by zarifpour** [comment]
> Yeah i meant how do you check the extension is loaded in zed

1. Clone the repo.
2. Move the `zed-solidity` directory to `~/Library/Application Support/Zed/extensions/installed`.
3. cd into the relocated repo.
4. Run `make`.
5. Restart Zed or reload the extensions via command pallet.

You should see solidity as an option as seen in the GIF.

Note that this issue exists: https://github.com/zed-industries/extensions/issues/124

**Comment by zarifpour** [comment]
I accidentally did not delete the `grammars/solidity.toml` and it was also incorrectly configured in the `Makefile`.
