### ISSUE TITLE
Forge dependencies

### ISSUE THREAD

**Issue by roderik** [zarifpour/zed-solidity#13]
Any guidance on how to get the plugin to find dependencies, preferably via the remapping.txt file?

**Comment by vgeddes** [comment]
The hardhat LSP [claims](https://github.com/NomicFoundation/hardhat-vscode/tree/development/server#foundry-experimental) to lookup remappings automatically. However in my case, it doesn't seem to work.

**Comment by vgeddes** [comment]
Works for me after actually making sure the dependencies were downloaded via `forge install`. The hardhat LSP calls `forge remappings` to load the remappings.

**Comment by roderik** [comment]
Hmm, did not work in a turborepo monorepo, will try again
