### ISSUE TITLE
Extension doesn't work on macOS

### ISSUE THREAD

**Issue by daedlock** [zarifpour/zed-solidity#2]
<img width="1857" alt="image" src="https://github.com/zarifpour/zed-solidity/assets/842346/b3be53c9-af0e-4f66-9e4b-8202ba4464ce">

**Comment by zarifpour** [comment]
Thank you for reporting this!

It seems I accidentally deleted the `grammars/solidity.toml` file in this commit: https://github.com/zarifpour/zed-solidity/commit/d331e891eb068d098cbfb9f0e04c4b4c17e9c826

I have restored this file in the latest commit and pushed the update to the `zed/extensions` repo.

Please try again after this is merged: https://github.com/zed-industries/extensions/pull/281

**Comment by daedlock** [comment]
Thanks!

**Comment by zarifpour** [comment]
My pleasure. 

If you'd like to start using it now, you can follow the [🛠️ Development Setup](https://github.com/zarifpour/zed-solidity#%EF%B8%8F-development-setup).

When the extension is merged, you should be able to simply install it upon release.

**Comment by zarifpour** [comment]
Looking good on the latest version:

![CleanShot 2024-03-03 at 12 38 14 on Zed — example sol — zed-solidity@2x](https://github.com/zarifpour/zed-solidity/assets/16494335/a3d76c69-0551-4093-8afa-68c9a97ae74a)
