### ISSUE TITLE
Add support for `error` syntax

### ISSUE THREAD

**Issue by richardhenry** [zarifpour/zed-solidity#4]
The error syntax is not currently supported. For example:

```solidity
contract Foo {
    error Bar();
}
```

The error will not be highlighted (screenshot):

<img width="136" alt="Screenshot 2024-06-28 at 11 51 15 PM" src="https://github.com/zarifpour/zed-solidity/assets/63480/5fdd8903-b1bf-4a75-8790-02a8e162dac2">

**Comment by zarifpour** [comment]
Once the above is merged, should be good to go 👍

**Comment by zarifpour** [comment]
Thanks for opening this issue! Zed recently added support for language servers, so once this is merged, there will also be better support for Solidity development. Cheers 🍻
