### ISSUE TITLE
Comments don't produce valid solidity

### ISSUE THREAD

**Issue by brockelmore** [zarifpour/zed-solidity#7]
```solidity
contract A {
    /** some_nat_spec
    */
    function c(bytes32 s) public returns (bool) {
       return true;
    }
}
```
turns into invalid solidity => 
```solidity
/*contract A {
    /** some_nat_spec
    */
    function c(bytes32 s) public returns (bool) {
       return true;
    }
}*/
```

I think all that needs to be done is only have `line_comment` like zed's rust does in `languages/solidity/config.toml`:
https://github.com/zarifpour/zed-solidity/blob/f303fa5bc686d902efbd1595dd29bb6515f0be26/languages/solidity/config.toml#L5

This way it just prepends `//` to each line.

**Comment by zarifpour** [comment]
Thanks for reporting this! I'll look into it.

**Comment by zarifpour** [comment]
I can't seem to reproduce it with the example you gave:

![CleanShot 2024-07-04 at 00 26 08 on Zed — test sol — 21lst-foundry@2x](https://github.com/zarifpour/zed-solidity/assets/16494335/910b8008-c046-42cb-94e9-4a9f7012aa94)

When I hit save or format, nothing changes.

---

Do you have another example I could try to reproduce?

**Comment by brockelmore** [comment]
sorry that was a terrible explanation on my end, i should have specified

when you try to comment out the whole code in zed using the keyboard shortcut it uses a block comment instead of individual line comments. locally i patched the extension by deleting block comment line in config.toml but im not sure if that's sensible generally. it does produce line-by-line commenting out of code but i don't know of any knock-on affects of removing the block comment from config.

**Comment by zarifpour** [comment]
> sorry that was a terrible explanation on my end, i should have specified
> 
> when you try to comment out the whole code in zed using the keyboard shortcut it uses a block comment instead of individual line comments. locally i patched the extension by deleting block comment line in config.toml but im not sure if that's sensible generally. it does produce line-by-line commenting out of code but i don't know of any knock-on affects of removing the block comment from config. 

thank you for the clarification. 

same here. I'll look into it later today or tomorrow.

**Comment by zarifpour** [comment]
@brockelmore I think you solved the issue in https://github.com/zed-industries/extensions/issues/1002#issuecomment-2214746732.

I will push the changes to `v0.1.1`.

When I highlight the whole code in zed using the keyboard shortcut, individual line comments are now used.

![CleanShot_2024-07-09_20 24 51_Zed_001376](https://github.com/zarifpour/zed-solidity/assets/16494335/dfeda6f8-e6ff-49b3-8c57-89afe609e152)

---

Feel free to close if there's nothing else to fix here.
